version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./DockerfileFront
    ports:
      - "127.0.0.1:80:80"

  backend:
    env_file:
      - backend/.env
    build:
      context: .
      dockerfile: ./DockerfileBack
    ports:
      - "127.0.0.1:8000:80"